services:
  traefik:
    image: traefik:v3
    container_name: traefik
    command:
      - "--configFile=/etc/traefik/traefik.yml"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.metrics.address=:8082"
      - "--api.dashboard=true"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--log.level=INFO"
    ports:
      - "8080:80"
      - "8443:8443"
      - "8082:8082"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic:/etc/traefik/dynamic
      - ./certs:/certs
    networks:
      - frontend_net  

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    command: ["--base", "/logs"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - frontend_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`localhost`) && PathPrefix(`/logs`)"
      - "traefik.http.routers.dozzle.entrypoints=websecure"
      - "traefik.http.routers.dozzle.tls=true"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"

    
  app:
    image: nginx:alpine
    container_name: app
    networks:
      - frontend_net
      - backend_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=secure-cloud_frontend_net"
      - "traefik.http.routers.app.rule=Host(`localhost`) && PathPrefix(`/app`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.middlewares.app-stripprefix.stripprefix.prefixes=/app"
      - "traefik.http.routers.app.middlewares=app-stripprefix"
      - "traefik.http.services.app.loadbalancer.server.port=80"

  db:
    image: postgres:15
    container_name: db
    env_file:
      - .env
    networks:
      - backend_net
  
  
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak
    command: start-dev --http-relative-path=/auth
    env_file:
      - .env
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_DATABASE: appdb
      KC_DB_USERNAME: appuser
      KC_DB_PASSWORD: AppPass123!
      KC_HOSTNAME: https://localhost:8443/auth
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY_HEADERS: xforwarded
    networks:
      - frontend_net
      - backend_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=secure-cloud_frontend_net"
      - "traefik.http.routers.keycloak.rule=Host(`localhost`) && PathPrefix(`/auth`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - frontend_net
      - backend_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=secure-cloud_frontend_net"
      - "traefik.http.routers.prometheus.rule=Host(`localhost`) && PathPrefix(`/prometheus`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.middlewares.prometheus-stripprefix.stripprefix.prefixes=/prometheus"
      - "traefik.http.routers.prometheus.middlewares=prometheus-stripprefix"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SERVER_ROOT_URL: "https://localhost:8443/grafana/"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    networks:
      - frontend_net
      - backend_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=secure-cloud_frontend_net"
      - "traefik.http.routers.grafana.rule=Host(`localhost`) && PathPrefix(`/grafana`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

networks:
  frontend_net:
  backend_net:
    internal: true
